# Generated by Django 2.2 on 2019-04-27 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_auto_20190427_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchants_user_email', models.EmailField(max_length=254)),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookinguser_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_merchant_id', models.CharField(max_length=100)),
                ('transaction_id', models.CharField(max_length=100)),
                ('stay', models.CharField(choices=[(None, '---- Please choose stay type ----'), ('hourly', 'hourly'), ('day', 'day')], max_length=45)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('meta_data', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.RemoveField(
            model_name='room',
            name='price',
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[(None, '---- Please choose status ----'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], max_length=45)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_by', to='api.BookingUser')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_payment', to='api.Payment')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_room', to='api.Room')),
            ],
        ),
        migrations.CreateModel(
            name='RoomPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stay', models.CharField(choices=[(None, '---- Please choose stay type ----'), ('hourly', 'hourly'), ('day', 'day')], max_length=45)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roomprice_room', to='api.Room')),
            ],
            options={
                'unique_together': {('room', 'stay')},
            },
        ),
    ]
