# Generated by Django 2.2 on 2019-06-06 15:14

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190501_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='stay',
        ),
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Hotel discription'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_type',
            field=models.CharField(choices=[(None, '---- Please choose hotel type ----'), ('3 star', '3 star'), ('4 star', '4 star'), ('5 star', '5 star'), ('7 star', '7 star')], max_length=45),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[(None, '---- Please choose room ----'), ('1', 'single room'), ('2', 'double room'), ('4', 'couples'), ('3', 'family')], max_length=45),
        ),
        migrations.AlterUniqueTogether(
            name='roomprice',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='roomprice',
            name='stay',
        ),
    ]
