# Generated by Django 2.2 on 2019-06-07 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190606_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomprice',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roomprice_room', to='api.Room'),
        ),
    ]
