# Generated by Django 2.2 on 2019-06-08 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190608_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_merchant_id',
        ),
    ]
